"use client";

import { useMemo, useState } from "react";
import { Plus, Search, Pencil, Trash2, X, CheckCircle2 } from "lucide-react";
import { useRouter } from "next/navigation";

type F = { id:string; code:string; zone_id:string; owner_id:string; current_stage:string; progress:number; status:string };
type Z = { id:string; name:string; owner_id:string };
type U = { id:string; full_name:string; role:string };

export function FoundationManager({ foundations, zones, users, commander }: { foundations:F[]; zones:Z[]; users:U[]; commander:boolean }) {
  const router = useRouter();
  const [q,setQ]=useState(""); const [zone,setZone]=useState(""); const [owner,setOwner]=useState("");
  const [adding,setAdding]=useState(false); const [editing,setEditing]=useState<F|null>(null); const [deleting,setDeleting]=useState<F|null>(null);
  const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const leaders=users.filter(u=>u.role==="leader");
  const shown=useMemo(()=>foundations.filter(f=>(!q||f.code.toLowerCase().includes(q.toLowerCase()))&&(!zone||f.zone_id===zone)&&(!owner||f.owner_id===owner)),[foundations,q,zone,owner]);
  const zoneName=(id:string)=>zones.find(z=>z.id===id)?.name||id; const ownerName=(id:string)=>users.find(u=>u.id===id)?.full_name||"Chưa giao";
  async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);const r=await fetch("/api/foundations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({codes:fd.get("codes"),zoneId:fd.get("zone"),ownerId:fd.get("owner")})});const j=await r.json();setBusy(false);if(!r.ok){setNotice(j.error);return}setAdding(false);setNotice(`Đã thêm ${j.count} móng`);router.refresh();}
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);const fd=new FormData(e.currentTarget);const r=await fetch(`/api/foundations/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({code:fd.get("code"),zoneId:fd.get("zone"),ownerId:fd.get("owner"),stage:fd.get("stage"),progress:fd.get("progress"),status:fd.get("status")})});const j=await r.json();setBusy(false);if(!r.ok){setNotice(j.error);return}setEditing(null);setNotice("Đã cập nhật móng");router.refresh();}
  async function remove(){if(!deleting)return;setBusy(true);const r=await fetch(`/api/foundations/${deleting.id}`,{method:"DELETE"});const j=await r.json();setBusy(false);if(!r.ok){setNotice(j.error);return}setDeleting(null);setNotice("Đã xóa móng");router.refresh();}
  return <>
    <section className="panel foundation-toolbar"><div className="foundation-filter"><label><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm mã móng..."/></label><select value={zone} onChange={e=>setZone(e.target.value)}><option value="">Tất cả khu vực</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select>{commander?<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Tất cả đội</option>{leaders.map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select>:null}</div>{commander?<button className="button primary" onClick={()=>setAdding(true)}><Plus size={18}/> Thêm móng</button>:null}</section>
    <div className="foundation-summary"><strong>{shown.length}</strong><span>móng đang hiển thị</span></div>
    <div className="foundation-table-wrap"><table className="foundation-table"><thead><tr><th>Mã móng</th><th>Khu vực</th><th>Đội phụ trách</th><th>Công việc</th><th>Tiến độ</th><th>Trạng thái</th>{commander?<th>Thao tác</th>:null}</tr></thead><tbody>{shown.map(f=><tr key={f.id}><td><b>{f.code}</b></td><td>{zoneName(f.zone_id)}</td><td>{ownerName(f.owner_id)}</td><td>{f.current_stage}</td><td><div className="foundation-progress-cell"><div className="progress-track"><i style={{width:`${Math.min(100,Number(f.progress))}%`}}/></div><b>{Number(f.progress).toFixed(0)}%</b></div></td><td><span className={`foundation-status ${f.status}`}>{f.status==="completed"?"Hoàn thành":f.status==="not_started"?"Chưa thi công":"Đang thi công"}</span></td>{commander?<td><div className="report-actions"><button className="report-action-button" onClick={()=>setEditing(f)}><Pencil size={15}/> Sửa</button><button className="report-action-button danger" onClick={()=>setDeleting(f)}><Trash2 size={15}/> Xóa</button></div></td>:null}</tr>)}</tbody></table>{!shown.length?<div className="empty-state">Không có móng phù hợp.</div>:null}</div>
    {adding?<div className="confirm-layer"><form className="foundation-modal" onSubmit={add}><button type="button" className="modal-close" onClick={()=>setAdding(false)}><X/></button><h2>Thêm móng</h2><label className="field"><span>Mã móng</span><textarea name="codes" required rows={5} placeholder={"M01, M02, M03\nCó thể nhập nhiều mã cùng lúc"}/></label><label className="field"><span>Khu vực</span><select name="zone" required defaultValue=""><option value="" disabled>Chọn khu vực</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label><label className="field"><span>Đội phụ trách</span><select name="owner" required defaultValue=""><option value="" disabled>Chọn đội</option>{leaders.map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select></label><button disabled={busy} className="button primary" type="submit">{busy?"Đang lưu...":"Lưu danh sách móng"}</button></form></div>:null}
    {editing?<div className="confirm-layer"><form className="foundation-modal" onSubmit={save}><button type="button" className="modal-close" onClick={()=>setEditing(null)}><X/></button><h2>Sửa {editing.code}</h2><div className="form-grid two"><label className="field"><span>Mã móng</span><input name="code" defaultValue={editing.code} required/></label><label className="field"><span>Tiến độ (%)</span><input name="progress" type="number" min="0" max="100" defaultValue={editing.progress}/></label></div><label className="field"><span>Khu vực</span><select name="zone" defaultValue={editing.zone_id}>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label><label className="field"><span>Đội phụ trách</span><select name="owner" defaultValue={editing.owner_id}>{leaders.map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select></label><label className="field"><span>Công việc hiện tại</span><input name="stage" defaultValue={editing.current_stage}/></label><label className="field"><span>Trạng thái</span><select name="status" defaultValue={editing.status}><option value="not_started">Chưa thi công</option><option value="in_progress">Đang thi công</option><option value="completed">Hoàn thành</option></select></label><button disabled={busy} className="button primary" type="submit">{busy?"Đang lưu...":"Lưu thay đổi"}</button></form></div>:null}
    {deleting?<div className="confirm-layer"><div className="confirm-card"><Trash2 size={25}/><h3>Xóa móng {deleting.code}?</h3><p>Thao tác này xóa móng khỏi danh mục quản lý.</p><div className="confirm-actions"><button className="button secondary" onClick={()=>setDeleting(null)}>Hủy</button><button className="button danger-button" disabled={busy} onClick={remove}>{busy?"Đang xóa...":"Xóa móng"}</button></div></div></div>:null}
    {notice?<div className="operation-popup ok"><div className="operation-popup-icon"><CheckCircle2/></div><div className="operation-popup-copy"><strong>{notice}</strong></div><button className="operation-popup-close" onClick={()=>setNotice("")}><X size={17}/></button></div>:null}
  </>;
}
